frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

uam_document:
    resource: "@UAMStructuredDocumentBundle/Controller"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"